### ISSUE TITLE
Claim is not available in action filter

### ISSUE THREAD

**Issue by epitka** [jabbera/aspnetcore-testing-role-handler#23]
I set up my test like this

```
var client = this.factory.CreateClient();

var customerId = Guid.NewGuid();
this.factory.RoleConfig.AddClaim(new Claim(Scopes.CustomerId, customerId.ToString()));
```

and we have a request filter like this

```
 public class CustomerRequestFilter : IActionFilter
    {
       public void OnActionExecuting(ActionExecutingContext context)
        {
           if (context.HttpContext.User.Identity.IsAuthenticated)
            {
                // Extract the CustomerId out of the User Claims and inject it in to the Request
                var value = context.HttpContext.User.FindFirstValue(Scopes.CustomerId);

              ...!!! neither User.Claims or doing it with FindFirstValue finds added claim. Only claim available is Name
          
             }
    }
}
```

It does not find newly added claim CustomerId. If I debug only available claim is Name

**Comment by jabbera** [comment]
I've not used these filters before. I'll look into it.

**Comment by jabbera** [comment]
@epitka I snapshot the RoleConfig when the client is created and add the claims to to http header. Since you are adding the roles after the client is configured they are missed. If you add the roles before you create the client the role should be available. If you need the ability to augment the roles after the client is configured I'd be happy to add it. Just let me know.
